#!/bin/sh
# Do the files in the image still match what their packages installed?
#
# dpkg --verify compares every file against the md5sum recorded at install
# time. On this image it reports about 14,000 differences, which sounds alarming
# and is almost entirely the build deliberately deleting documentation and
# translations to shrink the squashfs. The useful signal is what is left after
# those are set aside:
#
#   - files whose *contents* changed after the package installed them, and
#   - files reported missing from somewhere other than the stripped trees.
#
# Both are listed explicitly below. Anything outside those lists is a file that
# changed without anyone writing down why, which is the thing worth catching:
# it means the image no longer matches its package metadata, so an upgrade of
# that package will either revert the change or prompt about a conffile nobody
# remembers editing.
. "$(dirname "$0")/lib.sh"
mount_image "$@"

command -v dpkg >/dev/null || skip "dpkg not installed on the build host"
[ -f "$ROOT/var/lib/dpkg/status" ] || skip "no dpkg database in the image"

dpkg --root="$ROOT" --verify > "$WORK/verify" 2>"$WORK/verify.err" || true

echo "-- the check is actually running"
# dpkg --verify can only compare files it has md5sums for. If the build stripped
# /var/lib/dpkg/info the command would succeed while checking almost nothing, so
# the coverage is asserted before anything is concluded from the result.
NPKG=$(grep -c '^Package:' "$ROOT/var/lib/dpkg/status")
NSUM=$(ls "$ROOT"/var/lib/dpkg/info/*.md5sums 2>/dev/null | wc -l | tr -d ' ')
echo "   $NSUM of $NPKG packages carry md5sums"
[ "$NSUM" -gt $((NPKG / 2)) ] \
	&& _pass "most packages can be verified at all" \
	|| _fail "most packages can be verified at all" "only $NSUM of $NPKG have md5sums"

echo "-- packages are in a coherent state"
dpkg --root="$ROOT" --audit > "$WORK/audit" 2>&1 || true
assert_equal "dpkg --audit reports nothing" "" "$(cat "$WORK/audit")"
BADSTATE=$(awk '/^Package:/{p=$2} /^Status:/{if ($0 !~ /install ok installed/) print p}' \
	"$ROOT/var/lib/dpkg/status" | tr '\n' ' ')
assert_empty "every package is fully installed" "$BADSTATE"

echo "-- deleted files are only in the trees the build strips"
# The build removes documentation, manual pages, locales and info files. Those
# deletions are expected; a deletion anywhere else is not.
STRIPPED='^/usr/share/(doc|doc-base|man|info|locale|help|gnome/help)/'
UNEXPECTED_MISSING=$(awk '$1=="missing"{print $NF}' "$WORK/verify" \
	| grep -Ev "$STRIPPED" | sort -u)
NMISS=$(awk '$1=="missing"' "$WORK/verify" | wc -l | tr -d ' ')
echo "   $NMISS files reported missing in total"
# /opt/tmp holds build scratch from a DebianDog package and is removed during
# cleaning; the package still lists it, so it shows up here.
UNEXPECTED_MISSING=$(echo "$UNEXPECTED_MISSING" | grep -v '^/opt/tmp' | tr '\n' ' ')
assert_empty "nothing is missing outside the stripped trees" "$UNEXPECTED_MISSING"

echo "-- files whose contents changed since their package installed them"
# Expected, with the reason each one is here:
#   /etc/skel/.profile          conffile, build sets the live user's environment
#   /etc/rc.local               conffile, the live system's startup hook
#   /etc/X11/app-defaults/XTerm conffile, build's terminal defaults
#   /etc/cryptsetup-initramfs/conf-hook  conffile, encrypted-changes support
#   /usr/share/pixmaps/debian-logo.png   rebranding
#   /usr/share/icons/hicolor/icon-theme.cache  regenerated by gtk-update-icon-cache
KNOWN_CHANGED="
/etc/skel/.profile
/etc/rc.local
/etc/X11/app-defaults/XTerm
/etc/cryptsetup-initramfs/conf-hook
/usr/share/pixmaps/debian-logo.png
/usr/share/icons/hicolor/icon-theme.cache
"
# Not expected, and not accepted either - see the xfail below.
STALE_KEYRINGS="
/usr/share/keyrings/devuan-archive-keyring.pgp
/usr/share/keyrings/devuan-keyring.pgp
/usr/share/keyrings/devuan-removed-keys.pgp
"
CHANGED=$(awk '$1!="missing"{print $NF}' "$WORK/verify" | sort -u)
UNEXPECTED_CHANGED=""
for f in $CHANGED; do
	echo "$KNOWN_CHANGED"   | grep -qx -- "$f" && continue
	echo "$STALE_KEYRINGS"  | grep -qx -- "$f" && continue
	UNEXPECTED_CHANGED="$UNEXPECTED_CHANGED $f"
done
assert_empty "no undocumented content change" "$(echo $UNEXPECTED_CHANGED)"

echo "-- the Devuan archive keyrings are the ones their package installed"
# They are not. build-trixie does
#
#     cp -af ../dog-boot-trixie-20240602/* chroot/
#
# and that overlay carries its own copies of these three keyrings from 2024.
# /usr/share/keyrings/devuan-archive-keyring.gpg is a symlink to the .pgp, so
# the copy writes *through* the symlink and silently replaces the file the
# devuan-keyring package installed. The result has fewer keys than the package
# ships - 6 against 8 in the archive keyring - so the image verifies Devuan
# package signatures against a stale set of keys while dpkg believes the
# current package is installed.
#
# Left as a marker rather than fixed here: removing three files from the
# overlay changes what the build produces, and that is a decision about the
# build, not about the test. Deleting them makes this XPASS and the marker has
# to go with it.
# True when the file is absent from the changed list, i.e. when it does match
# what the package installed. Written as a function because the condition is
# "not present", and an inline `grep -v` gets that backwards: grep -v succeeds
# whenever *any* other line differs, so it is true no matter what.
matches_package() { ! echo "$CHANGED" | grep -qx -- "$1"; }
for f in $STALE_KEYRINGS; do
	xfail "$(basename "$f") matches devuan-keyring" matches_package "$f"
done

echo "-- and the list of expected changes has not gone stale"
for f in $KNOWN_CHANGED; do
	echo "$CHANGED" | grep -qx -- "$f" \
		|| _fail "$f is still listed as changed" "it no longer differs - drop it from the list"
done
_pass "every documented change is still present"

finish
