#!/bin/sh
# Do the files in the image still match what their packages installed?
#
# dpkg --verify compares every file against the md5sum recorded at install
# time. On this image it reports about 14,000 differences, which sounds alarming
# and is almost entirely the build deliberately deleting documentation and
# translations to shrink the squashfs. The useful signal is what is left after
# those are set aside:
#
#   - files whose *contents* changed after the package installed them, and
#   - files reported missing from somewhere other than the stripped trees.
#
# Both are listed explicitly below. Anything outside those lists is a file that
# changed without anyone writing down why, which is the thing worth catching:
# it means the image no longer matches its package metadata, so an upgrade of
# that package will either revert the change or prompt about a conffile nobody
# remembers editing.
. "$(dirname "$0")/lib.sh"
mount_image "$@"

command -v dpkg >/dev/null || skip "dpkg not installed on the build host"
[ -f "$ROOT/var/lib/dpkg/status" ] || skip "no dpkg database in the image"

dpkg --root="$ROOT" --verify > "$WORK/verify" 2>"$WORK/verify.err" || true

echo "-- the check is actually running"
# dpkg --verify can only compare files it has md5sums for. If the build stripped
# /var/lib/dpkg/info the command would succeed while checking almost nothing, so
# the coverage is asserted before anything is concluded from the result.
NPKG=$(grep -c '^Package:' "$ROOT/var/lib/dpkg/status")
NSUM=$(ls "$ROOT"/var/lib/dpkg/info/*.md5sums 2>/dev/null | wc -l | tr -d ' ')
echo "   $NSUM of $NPKG packages carry md5sums"
[ "$NSUM" -gt $((NPKG / 2)) ] \
	&& _pass "most packages can be verified at all" \
	|| _fail "most packages can be verified at all" "only $NSUM of $NPKG have md5sums"

echo "-- packages are in a coherent state"
dpkg --root="$ROOT" --audit > "$WORK/audit" 2>&1 || true
assert_equal "dpkg --audit reports nothing" "" "$(cat "$WORK/audit")"
# "deinstall ok config-files" is a removed package whose conffiles remain. That
# is the normal end state after swapping init systems - the Debian/systemd image
# carries initscripts, insserv and sysv-rc in exactly that state because
# systemd-sysv displaced them - and it is not a broken install. Only genuinely
# incomplete states matter here: half-installed, unpacked, half-configured,
# triggers-pending.
BADSTATE=$(awk '/^Package:/{p=$2}
	/^Status:/{ if ($0 !~ /install ok installed/ && $0 !~ /deinstall ok config-files/) print p }' \
	"$ROOT/var/lib/dpkg/status" | tr '\n' ' ')
assert_empty "no package is left half-installed" "$BADSTATE"
# The exclusion must not be a blanket one: a package stuck half-configured has
# to still fail, so check the pattern only tolerates the removed-with-conffiles
# state.
assert_equal "the tolerated state is only 'deinstall ok config-files'" "" \
	"$(awk '/^Status:/{if ($0 ~ /half-installed|half-configured|unpacked|triggers-pending/) print}' \
		"$ROOT/var/lib/dpkg/status" | head -1)"

echo "-- deleted files are only in the trees the build strips"
# The build removes documentation, manual pages, locales and info files. Those
# deletions are expected; a deletion anywhere else is not.
# The udev vendor-name tables (20-OUI, 20-pci-vendor-model, 20-usb-vendor-model
# and friends) are deleted as well and hwdb.bin rebuilt without them; that
# file is generated, not shipped, so only the tables show up here.
STRIPPED='^/usr/share/(doc|doc-base|man|info|locale|help|gnome/help)/|^/usr/lib/udev/hwdb\.d/20-(OUI|pci-vendor-model|usb-vendor-model|bluetooth-vendor-product|acpi-vendor)\.hwdb$'
UNEXPECTED_MISSING=$(awk '$1=="missing"{print $NF}' "$WORK/verify" \
	| grep -Ev "$STRIPPED" | sort -u)
NMISS=$(awk '$1=="missing"' "$WORK/verify" | wc -l | tr -d ' ')
echo "   $NMISS files reported missing in total"
# /opt/tmp holds build scratch from a DebianDog package and is removed during
# cleaning; the package still lists it, so it shows up here.
UNEXPECTED_MISSING=$(echo "$UNEXPECTED_MISSING" | grep -v '^/opt/tmp' | tr '\n' ' ')
assert_empty "nothing is missing outside the stripped trees" "$UNEXPECTED_MISSING"

echo "-- files whose contents changed since their package installed them"
# Expected, with the reason each one is here:
#   /etc/skel/.profile          conffile, build sets the live user's environment
#   /etc/rc.local               conffile, the live system's startup hook
#   /etc/X11/app-defaults/XTerm conffile, build's terminal defaults
#   /etc/cryptsetup-initramfs/conf-hook  conffile, encrypted-changes support
#   /usr/share/pixmaps/debian-logo.png   rebranding
#   /usr/share/icons/hicolor/icon-theme.cache  regenerated by gtk-update-icon-cache
KNOWN_CHANGED="
/etc/skel/.profile
/etc/rc.local
/etc/X11/app-defaults/XTerm
/etc/cryptsetup-initramfs/conf-hook
/usr/share/pixmaps/debian-logo.png
/usr/share/icons/hicolor/icon-theme.cache
"
CHANGED=$(awk '$1!="missing"{print $NF}' "$WORK/verify" | sort -u)
UNEXPECTED_CHANGED=""
for f in $CHANGED; do
	echo "$KNOWN_CHANGED" | grep -qx -- "$f" && continue
	UNEXPECTED_CHANGED="$UNEXPECTED_CHANGED $f"
done
# The Devuan archive keyrings used to appear here. The dog-boot overlay carried
# 2024 copies of devuan-archive-keyring, devuan-keyring and devuan-removed-keys,
# and `cp -af ../dog-boot-trixie-20240602/* chroot/` wrote them through the
# .gpg -> .pgp symlinks over the files the devuan-keyring package installed -
# leaving the image verifying Devuan signatures against six keys where the
# package ships eight. Those three overlay files are gone, so a keyring in this
# list is now a real regression rather than a known one.
assert_empty "no undocumented content change" "$(echo $UNEXPECTED_CHANGED)"

echo "-- and the list of expected changes has not gone stale"
for f in $KNOWN_CHANGED; do
	echo "$CHANGED" | grep -qx -- "$f" \
		|| _fail "$f is still listed as changed" "it no longer differs - drop it from the list"
done
_pass "every documented change is still present"

finish
